---
- name: Pull docker image
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: kdesh2001/calculator_devops:latest
        source: pull
