---
- name: Pull docker image
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: kdesh2001/calculator_devops:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Creating container
      shell: docker create -it --name Calculator kdesh2001/calculator_devops
